# Generated by Django 5.1.1 on 2024-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
