# Generated by Django 5.1.1 on 2024-09-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_media_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('f', 'Finished'), ('ip', 'In Progress'), ('p', 'Planning'), ('dr', 'Dropped')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('r', 'Recommended'), ('nr', 'Not Recommended'), ('otf', 'On The Fence'), ('n/a', 'Not Rated')], max_length=3),
        ),
    ]
